### ISSUE TITLE
Display the NFT image of ERC-721

### ISSUE THREAD

**Issue by fabiooshiro** [Calindra/cartesi-store#8]

**Comment by fabiooshiro** [comment]
https://docs.opensea.io/docs/metadata-standards

**Comment by fabiooshiro** [comment]
Transform the IPFS protocol URL to use a gateway, such as https://ipfs.io/ipfs/bafybeifx7yeb55armcsxwwitkymga5xf53dxiarykms3ygqic223w5sk3m#x-ipfs-companion-no-redirect.

So ipfs://<CID> should be transformed to https://ipfs.io/ipfs/<CID>

**Comment by vscatarino** [comment]
- read local images 
- create one JSON per collection and associate an image with the JSON.
- json should be identifier with some id
